### ISSUE TITLE
Background image name, please :(

### ISSUE THREAD

**Issue by phanlong2811** [ps173/vimrc-dotfiles#1]
Can you give me the background image, plz :(

**Comment by ps173** [comment]
Lol ok 
here's the one for herbstluftwm - [edena something](https://wallhere.com/fr/wallpaper/101432)    
here's the one for awesomewm - sorry I will find It soon and update it I apologize    
and here's the one for openbox - [mountains and pinkish stuff](https://wallhaven.cc/w/wyw7d7)
